USE C4707F18G120;
DROP TABLE IF EXISTS SEES;
DROP TABLE IF EXISTS PROVIDES;
DROP TABLE IF EXISTS PRIMARY_PROVIDER;
DROP TABLE IF EXISTS SERVICE_PROVIDER;
DROP TABLE IF EXISTS DIAGNOSIS;
DROP TABLE IF EXISTS USES;
DROP TABLE IF EXISTS SUPPLIES;
DROP TABLE IF EXISTS RECEIVES;
DROP TABLE IF EXISTS TREATMENT;
DROP TABLE IF EXISTS INSURED_BY;
DROP TABLE IF EXISTS INSURANCE_PROVIDER;
DROP TABLE IF EXISTS FOLLOW_UP_ORDERS;
DROP TABLE IF EXISTS MEDICATIONS;
DROP TABLE IF EXISTS MEDICAL_COND;
DROP TABLE IF EXISTS INITIAL_ASSESSMENT;
DROP TABLE IF EXISTS NURSE;
DROP TABLE IF EXISTS REFERRAL;
DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS CLERK;
DROP Table IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT (
	Dept_name	varchar(255),
    PRIMARY KEY(Dept_name)
);


CREATE TABLE EMPLOYEE (
	Employee_Id	INT,
    EName	varchar(255),
    Dept_Name	varchar(255)			NOT NULL,
    PRIMARY KEY(Employee_Id),
    UNIQUE KEY(EName),
    FOREIGN KEY(Dept_Name) REFERENCES DEPARTMENT(Dept_name)
);
CREATE TABLE CLERK (
	Employee_Id	int			NOT NULL,
    CName	varchar(255),
    PRIMARY KEY(Employee_Id),
    FOREIGN KEY(Employee_Id) REFERENCES EMPLOYEE(Employee_Id),
    FOREIGN KEY(CName) REFERENCES EMPLOYEE(EName)
);
CREATE TABLE PATIENT
	(Pid				INT			NOT NULL,
	 P_Name				VARCHAR(15)			NOT NULL,
	 P_Address			VARCHAR(100),
	 PhoneNo			VARCHAR(15),
	 EmerCont_Info		VARCHAR(15),
     DoB				DATE,
     Insurance_Info		VARCHAR(15),
     Less_than_18		BOOL,
     ParGuard_Info		VARCHAR(15),
     Clerk_id			INT			NOT NULL,
	PRIMARY KEY(Pid),
	FOREIGN KEY(Clerk_id) REFERENCES CLERK(Employee_Id));
CREATE TABLE REFERRAL
	(Pid				INT			NOT NULL,
	 Ref_id				INT			NOT NULL,
    PRIMARY KEY(Pid, REF_id),
	FOREIGN KEY (Pid) REFERENCES PATIENT(Pid));
CREATE TABLE NURSE (
	Employee_Id	int,
    NName	varchar(255)			NOT NULL,
    PRIMARY KEY(Employee_Id),
    FOREIGN KEY(Employee_Id) REFERENCES EMPLOYEE(Employee_Id),
    FOREIGN KEY(NName) REFERENCES EMPLOYEE(EName)
);
CREATE TABLE INITIAL_ASSESSMENT
	(Pid				INT,
     Visit_day			DATE,
     Nurse_id			INT NOT NULL,
     Height				INT,
     Weight				DECIMAL,
     Blood_press		INT,
     Temp				DECIMAL,
	PRIMARY KEY(Pid, Visit_day),
	FOREIGN KEY (Pid) REFERENCES PATIENT(Pid),
	FOREIGN KEY(Nurse_id) REFERENCES NURSE(Employee_Id));
CREATE TABLE MEDICAL_COND
	(Pid				INT,
     Visit_day			DATE,
     Med_conds			VARCHAR(250) 	NOT NULL,
	PRIMARY KEY(Pid, Visit_day),
	FOREIGN KEY(Pid, Visit_day) REFERENCES INITIAL_ASSESSMENT(Pid, Visit_day)
	);
CREATE TABLE MEDICATIONS
		(Pid			INT,
		 Visit_day		DATE			NOT NULL,
         Meds			VARCHAR(250)			NOT NULL,
		PRIMARY KEY (Pid, Visit_day),
        FOREIGN KEY (Pid, Visit_day) REFERENCES INITIAL_ASSESSMENT(Pid, Visit_day));
CREATE TABLE FOLLOW_UP_ORDERS
		(Pid			INT			NOT NULL,
		 FU_ICD_10PCS	INT			NOT NULL,
         f_name			VARCHAR(15)			NOT NULL,
         f_location		VARCHAR(15)			NOT NULL,
         f_phone_number	VARCHAR(15)			NOT NULL,
		PRIMARY KEY (Pid, FU_ICD_10PCS),
        FOREIGN KEY (Pid) REFERENCES PATIENT(Pid));
CREATE TABLE INSURANCE_PROVIDER
	(IP_ID		INT		NOT NULL,
    PRIMARY KEY(IP_ID));
CREATE TABLE INSURED_BY
		(Pid			INT			NOT NULL,
         IP_ID			INT			NOT NULL,
         Start_date		DATE			NOT NULL,
         End_date		DATE			NOT NULL,
		PRIMARY KEY (Pid, IP_ID),
        FOREIGN KEY (Pid) REFERENCES PATIENT(Pid),
        FOREIGN KEY (IP_ID) REFERENCES INSURANCE_PROVIDER(IP_ID));
CREATE TABLE TREATMENT
	(ICD_10_PCS	INT		NOT NULL,
    T_name		VARCHAR(15),
    Total_cost	DECIMAL(10,2),
    PRIMARY KEY(ICD_10_PCS));
CREATE TABLE RECEIVES
	(Pid		INT		NOT NULL,
    ICD_10_PCS	INT		NOT NULL,
    PRIMARY KEY(Pid, ICD_10_PCS),
	FOREIGN KEY(Pid) REFERENCES PATIENT(Pid),
	FOREIGN KEY(ICD_10_PCS) REFERENCES TREATMENT(ICD_10_PCS));
CREATE TABLE SUPPLIES
	(Item_Id	INT		NOT NULL,
    Sup_name	VARCHAR(15)			NOT NULL,
    Billable	BOOL			NOT NULL,
    Cost		DECIMAL(10,2),
    PRIMARY KEY(Item_Id));
CREATE TABLE USES
	(ICD_10_PCS	INT		NOT NULL,
    Item_Id		INT		NOT NULL,
    PRIMARY KEY(ICD_10_PCS, Item_Id),
	FOREIGN KEY(Item_Id) REFERENCES SUPPLIES(Item_Id),
	FOREIGN KEY(ICD_10_PCS) REFERENCES TREATMENT(ICD_10_PCS));

CREATE TABLE DIAGNOSIS (
	ICD_10_CMS	int,
    DName	varchar(255),
    PRIMARY KEY(ICD_10_CMS)
);
CREATE TABLE SERVICE_PROVIDER (
	SP_ID	int			NOT NULL,
    SPName	varchar(255)			NOT NULL,
    PRIMARY KEY(SP_ID),
	FOREIGN KEY(SP_ID) REFERENCES EMPLOYEE(Employee_Id),
	FOREIGN KEY(SPName) REFERENCES EMPLOYEE(EName)
);
CREATE TABLE PRIMARY_PROVIDER (
	SP_ID	int			NOT NULL,
    PPName	varchar(255)			NOT NULL,
    PRIMARY KEY(SP_ID),
    FOREIGN KEY(SP_ID) REFERENCES SERVICE_PROVIDER(SP_ID),
    FOREIGN KEY(PPName) REFERENCES EMPLOYEE(EName)
);
CREATE TABLE PROVIDES
	(Pid				INT			NOT NULL,
	 SP_ID				INT			NOT NULL,
     ICD_10_CMS			INT			NOT NULL,
	PRIMARY KEY(Pid, SP_ID, ICD_10_CMS),
	FOREIGN KEY(Pid) REFERENCES PATIENT(Pid),
	FOREIGN KEY(SP_ID) REFERENCES PRIMARY_PROVIDER(SP_ID),
	FOREIGN KEY(ICD_10_CMS) REFERENCES DIAGNOSIS(ICD_10_CMS));
CREATE TABLE SEES
	(Pid				INT			NOT NULL,
     SP_ID				INT			NOT NULL,
	PRIMARY KEY(Pid, SP_ID),
	FOREIGN KEY(Pid) REFERENCES PATIENT(Pid),
	FOREIGN KEY(SP_ID) REFERENCES SERVICE_PROVIDER(SP_ID));
